### ISSUE TITLE
Print methods for easier understanding of objects

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#26]
e.g.,  

__point__

```r
lawn_point(c(-74.5, 40), properties = list(name = 'poly1', population = 400))
#> <Point>
#>   Long: -74.5
#>   Lat: 40
#>   Properties: 
#>      name: poly1
#>      population: 400
```

__polygon__

```r
lawn_polygon(rings, properties = list(name = 'poly1', population = 400))
#> <Polygon>
#>   No. points: 5
#>   Mean Long: -2.25134
#>   Mean Lat: 53.47442
#>   Properties: 
#>      name: poly1
#>      population: 400
```

thoughts @jhollist on these?   these are not so necessary for a single point or small polygon, but for large objects with lots of points, I wonder if we should use print methods, sort of like dplyr so that large data.frame's are easier to comprehend

**Comment by jhollist** [comment]
@sckott I like this.  

Couple of thoughts.  Instead of Mean Long, Lat, Returing the bounding box might be better.  From what I know of geojson (still not much), it isn't required but a bbox: member is allowable.  `sp` objects will have a bbox so that could be extracted and added in.  Or, could use turf.js extent (probably a better option) and have the bbox returned as part of all `lawn` objects.  

Lastly, when we return the Properties it will get unweildy with larger datasets.  Need to figure out how to return that.  The dplyr style might work or paired down str() for this.

Some of this may be good for a v0.2 release.  Get the print object working similar to how you have it now, and then add in bounding box stuff and a way to deal with objects with larger datasets.

**Comment by sckott** [comment]
@jhollist thanks for feedback. 

* Good point on bbox!  Totally forgot about that - can use turf.js to get that. 
* Agreed on properties that it can't get large quickly - right, we could coerce into a data.frame, then use dplyr tbl_df printing
* Sounds good to move to next milestone - good to get this to cran/blog post soon to generate more feedback

**Comment by sckott** [comment]
working on this, pain points

- `as_feature()`
- `lawn_combine()` - still need print methods for `multipoint`, `multipolygon`, and `multilinestring`
