### ISSUE TITLE
visualize

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#3]
It seems important to have an easy to use built in way to visualize outputs of various analyses in this pkg. 

@jhollist @lmullen I added a new fxn `view()` using `leaflet` - thoughts?

e.g.,, https://github.com/sckott/lawn#view

**Comment by jhollist** [comment]
:+1: 

I wrote something myself, but since I am new to this js thing did it with brute force.  I'll take a look at yours.  

Cheers,
Jeff

**Comment by lmullen** [comment]
I tried the `view()` function with the examples in the docs, and it works
for me.

**Comment by sckott** [comment]
@lmullen awesome, glad it works. 

open to any changes, just whipped that up quickly

**Comment by jhollist** [comment]
Works for me as well on the examples.

Would be nice to also get it working with the results returned from
lawn::random or lawn::buffer which is a list as opposed to the geojson
text.



On Thu, Mar 5, 2015 at 3:53 PM, Scott Chamberlain <notifications@github.com>
wrote:

> @lmullen <https://github.com/lmullen> awesome, glad it works.
>
> open to any changes, just whipped that up quickly
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sckott/lawn/issues/3#issuecomment-77449404>.
>



-- 
Jeff W. Hollister
email: jeff.w.hollister@gmail.com
google voice: 401 326 2531
cell: 401 556 4087

**Comment by sckott** [comment]
Right, we can rework so that `view` deploys on either a character string (`view.character`), or list (`view.list`), and maybe json (from jsonlite, `view.json`)

**Comment by sckott** [comment]
opened #4 to make it easier to pass in either a list of geojson or a character string

**Comment by jhollist** [comment]
@sckott view on list working great!  I need to look at that and see what you did.  

I tried getting that to work but didn't make much progress (becuase I don't know the geojson stuff well).

Now for a fun game, `view(buffer(random(5),100,"miles")`  to see what web mercator does.  These are supposed to look like circles...

**Comment by sckott** [comment]
@jhollist seems like it's time to open that issue on turf.js ?

**Comment by jhollist** [comment]
@sckott The change in shape is expected with web mercator.  leaflet tiles (and most all web map tiles) are in web mercator and that projection doesn't give a hoot about maintaining shape or area.  A great link that shows the behavior is [mercator puzzle](https://gmaps-samples.googlecode.com/svn/trunk/poly/puzzledrag.html)  shape and size are accurate near the equator and get more distorted as you move away.  Grab greenland (it starts out over south america) and move it to see what happens. 

The other issue with the smaller buffers does need to be opened.  I want to work up a jsfiddle example instead of showing the example with lawn.  Seems cleaner that way.

**Comment by sckott** [comment]
@jhollist ah, i seek, thanks for clarifying

**Comment by sckott** [comment]
closing this, seems good for now
