### ISSUE TITLE
c++ exception with r3.4

### ISSUE THREAD

**Issue by sckott** [ropensci/lawn#64]
these tests https://github.com/ropensci/lawn/blob/master/tests/testthat/test-centroid.R#L46-L50 throw error

```r
Error in context_eval(join(src), private$context) : 
  c++ exception (unknown reason)
```

**Comment by henargeo** [comment]
I get a similar error when using lawn_within, no matter whether I try with feature, featurecollection or polygon. 

Error in context_eval(join(src), private$context) : 
  TypeError: Cannot read property 'length' of undefined

Polygon was created with lawn_buffer, and area measured with lawn_area indicates it's incorrect (5 kilometers must be 78539816.34 m2 instead of the 5949399 m2 I'm getting).

Lawn_within seems to work ok with the sample dataset lawn_data.

Any help would be much appreciated,
Thanks!

**Comment by sckott** [comment]
thanks for the report @henargeo  - will report back soon

please share your `sessionInfo()` or `devtools::session_info()`

**Comment by sckott** [comment]
@henargeo try again after reinstalling `devtools::install_github("ropensci/lawn")`

part of problem is we can do a better job checking geojson types. within expects featurecollection's, - so added checks for that , and added ability to make featurecollection's from features, which we weren't supporting befiore, e.,g 

```r
pt <- '{
 "type": "Feature",
 "properties": {},
 "geometry": {
    "type": "Point",
    "coordinates": [-90.548630, 14.616599]
  }
}'
poly <- lawn_featurecollection(lawn_buffer(pt, 5))
pts <- lawn_featurecollection(lawn_point(c(-90.55, 14.62)))
lawn_within(pts, poly)
#> <FeatureCollection>
#>   Bounding box: -90.5 14.6 -90.5 14.6
#>   No. features: 1
#>   No. points: 2
#>   Properties: NULL
```

**Comment by henargeo** [comment]
Thanks a lot! I got lawn_within working properly now, though the buffer around the single point is an ellipse. I've tried to transform the coordinates and represent it with leaflet, but I haven't succeeded yet. I can't find a way to convert lawn_buffer output to geojson or spdf, I'll keep trying bu any suggstion is welcome.

**Comment by sckott** [comment]
> though the buffer around the single point is an ellipse

can you open a new issue for this and show an example?

> I can't find a way to convert lawn_buffer output to geojson or spdf

the output is geojson, but as list format. You can convert to JSON with `jsonlite::toJSON()` adjusting its params as you see fit. is `spdf` a `SpatialDataFrame` ?

**Comment by jhollist** [comment]
The ellipse is not unexpected.  The further N or S the location the less
circular the resultant polygon.    This is a function of the projection.

**Comment by sckott** [comment]
thanks @jhollist , makes sense

**Comment by sckott** [comment]
cran checks fail on osx only: https://cran.r-project.org/web/checks/check_results_lawn.html

**Comment by henargeo** [comment]
Thanks a lot for all your answers. 

Re the ellipse, I think the problem is that it's computing on geographic coordinates (epsg:4326) and plotting in projected (epsg:3857). That's why I'd like to transform it before plotting (since I don't find a way to keep epsg:3857 when converting to geojson).

So far, I'm trying to use sp::spTransform, which requieres a spatial data frame. This is the strunggling point right now, I'm unable to convert the output from lawn_buffer into a spatial data frame.

Trying: rgeosonio::geojson_sp
> bufferJSON = toJSON(buffer)
> buff = geojson_sp(bufferJSON)
Error in UseMethod("geojson_sp") : 
  no applicable method for 'geojson_sp' applied to an object of class "character"

Trying: sp::SpatialPolygonsDataFrame
> bufferSPDF = SpatialPolygonsDataFrame(bufferJSON)
Error in SpatialPolygonsDataFrame(bufferJSON) : 
  trying to get slot "polygons" from an object of a basic class ("character") with no slots

**Comment by jhollist** [comment]
I'm sure there is a better way to do it, but I think you can write the geojson out to a file and use readOGR to read in the geojson.  At a conference now so don't have time to figure out a more direct route ...

The projections is definitely the cause of the ellipse!

**Comment by henargeo** [comment]
Thanks for your help. I'm sorry I keep on asking about this, hope it helps someone else too.

Trying your suggestion comes to this:

> buffexported =  writeOGR(bufferJSON, driver='GeoJSON')
Error: inherits(obj, "Spatial") is not TRUE
> buffexported =  writeOGR(buffer, driver='GeoJSON')
Error: inherits(obj, "Spatial") is not TRUE

The large workaround it's been using rgeos::gBuffer and sp::over, but I'm really interested in learning lawn and using the extensive spatial analysis functions.

**Comment by sckott** [comment]
@henargeo did you know lawn has `view()` to plot using `leaflet` library  - but maybe you want base plots? or ggplots

**Comment by jeroen** [comment]
FYI the `c++ exception (unknown reason)` message is a bug in the CRAN compiler on for R 3.4 on OSX. https://github.com/jeroen/V8/issues/37. Not sure if the other problem above is related.

**Comment by sckott** [comment]
thanks @jeroen !
